// apps/csr-solidjs-apache/src/pages/Dynamic.tsx
import type { Component } from 'solid-js';
import { useParams } from '@solidjs/router';

const Dynamic: Component = () => {
  const params = useParams<{ name: string }>();

  return (
    <div>
      <h1>Hello World</h1>
      <p>Dynamic ID: {params.name}</p>
    </div>
  );
};

export default Dynamic;

// apps/csr-angular/src/app/dynamic/dynamic.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-dynamic',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div>
      <h1>Hello World</h1>
      <p>Dynamic ID: {{ name }}</p>
    </div>
  `
})
export class DynamicComponent {
  name: string = '';

  constructor(private route: ActivatedRoute) {
    this.route.params.subscribe(params => {
      this.name = params['name'];
    });
  }
}
