// subjects/csr-solid-nginx/src/pages/Dynamic.tsx
import { createSignal, type Component } from 'solid-js';
import { useParams } from '@solidjs/router';

const Dynamic: Component = () => {
  const params = useParams();
  const [count, setCount] = createSignal(0);

  return (
    <main>
      <h1>Hello World</h1>
      <p>Dynamic ID: {params.name}</p>
      <div>
        <p>Count: {count()}</p>
        <button onClick={() => setCount(count() + 1)}>Increment</button>
      </div>
    </main>
  );
};

export default Dynamic;

// apps/csr-react/src/pages/Dynamic.tsx
import { useState } from 'react';
import { useParams } from 'react-router-dom';

function Dynamic() {
  const { name } = useParams<{ name: string }>();
  const [count, setCount] = useState(0);

  return (
    <div>
      <h1>Hello World</h1>
      <p>Dynamic ID: {name}</p>
      <div>
        <p>Count: {count}</p>
        <button onClick={() => setCount(count + 1)}>Increment</button>
      </div>
    </div>
  );
}

export default Dynamic;
