// apps/ssr-angular/src/app/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  standalone: true,
  template: `
    <main>
      <h1>Hello World</h1>
      <div>
        <p>Count: {{ count }}</p>
        <button (click)="count = count + 1">Increment</button>
      </div>
    </main>
  `
})
export class HomeComponent {
  count = 0;
}

// apps/ssr-react-router/app/routes/home.tsx
import { useState } from 'react';
import type { Route } from "./+types/home";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Hello World" },
    { name: "description", content: "Hello World page" },
  ];
}

export default function Home() {
  const [count, setCount] = useState(0);

  return (
    <main>
      <h1>Hello World</h1>
      <div>
        <p>Count: {count}</p>
        <button onClick={() => setCount(count + 1)}>Increment</button>
      </div>
    </main>
  );
}
