// applications/ssr-nuxtjs-node/app/pages/dynamic/[name].vue
<script setup lang="ts">
const route = useRoute();
const name = route.params.name;
const count = ref(0);
</script>

<template>
  <main>
    <h1>Hello World</h1>
    <p>Dynamic ID: {{ name }}</p>
    <div>
      <p>Count: {{ count }}</p>
      <button @click="count++">Increment</button>
    </div>
  </main>
</template>

// subjects/ssr-qwik-city-node/src/routes/dynamic/[name]/index.tsx
import { component$, useSignal } from "@builder.io/qwik";
import { useLocation, type DocumentHead } from "@builder.io/qwik-city";

export default component$(() => {
  const loc = useLocation();
  const name = loc.params.name;
  const count = useSignal(0);

  return (
    <main>
      <h1>Hello World</h1>
      <p>Dynamic ID: {name}</p>
      <div>
        <p>Count: {count.value}</p>
        <button onClick$={() => count.value++}>Increment</button>
      </div>
    </main>
  );
});

export const head: DocumentHead = {
  title: "Dynamic Page",
  meta: [
    {
      name: "description",
      content: "Dynamic page with parameter",
    },
  ],
};
