// applications/ssr-nuxtjs-node/app/pages/dynamic/[name].vue
<script setup lang="ts">
const route = useRoute();
const name = route.params.name;
const count = ref(0);
</script>

<template>
  <main>
    <h1>Hello World</h1>
    <p>Dynamic ID: {{ name }}</p>
    <div>
      <p>Count: {{ count }}</p>
      <button @click="count++">Increment</button>
    </div>
  </main>
</template>

// subjects/ssr-nextjs-bun/src/app/dynamic/[name]/page.tsx
"use client";

import React, { useState, use } from 'react';

const HelloWorldPage = ({
  params,
}: {
  params: Promise<{ name: string }>;
}) => {
  const { name } = use(params);
  const [count, setCount] = useState(0);

  return (
    <main>
      <h1>Hello World</h1>
      <p>Dynamic ID: {name}</p>
      <div>
        <p>Count: {count}</p>
        <button onClick={() => setCount(count + 1)}>Increment</button>
      </div>
    </main>
  );
};

export default HelloWorldPage;
