// apps/ssr-solid-start/src/routes/dynamic/[name].tsx
import { createSignal } from 'solid-js';
import { useParams } from '@solidjs/router';

export default function DynamicPage() {
  const params = useParams();
  const [count, setCount] = createSignal(0);

  return (
    <main>
      <h1>Hello World</h1>
      <p>Dynamic ID: {params.name}</p>
      <div>
        <p>Count: {count()}</p>
        <button onClick={() => setCount(count() + 1)}>Increment</button>
      </div>
    </main>
  );
}

// applications/ssr-nuxtjs-node/app/pages/dynamic/[name].vue
<script setup lang="ts">
const route = useRoute();
const name = route.params.name;
const count = ref(0);
</script>

<template>
  <main>
    <h1>Hello World</h1>
    <p>Dynamic ID: {{ name }}</p>
    <div>
      <p>Count: {{ count }}</p>
      <button @click="count++">Increment</button>
    </div>
  </main>
</template>
